import {useEffect,useLayoutEffect,useMemo,useRef,useState} from "react";
import {Outlet,useLocation,useNavigate} from "react-router-dom";
import {ArrowLeft,BatteryMedium,ChevronLeft,Wifi,X} from "lucide-react";
import {GlobalMusicMiniPlayer} from "../core/musicPlayer";
import {calculateMobileHomeLayout,isMobileHomeFullCanvasEnvironment} from "../core/mobileHomeLayout";
import {trustedMobileHomeViewportHeight} from "../core/mobileHomeGeometry";
import {calculateMobileHomeFooterRecovery} from "../core/mobileHomeFooterRecovery";

export function PhoneShell(){
  const nav=useNavigate(),loc=useLocation();
  const [time,setTime]=useState(""),[keyboard,setKeyboard]=useState(0);
  const [nativeViewport,setNativeViewport]=useState(()=>typeof window!=="undefined"&&(((navigator.maxTouchPoints??0)>0||window.matchMedia("(hover: none) and (pointer: coarse)").matches)||Math.min(window.innerWidth,document.documentElement.clientWidth||window.innerWidth)<=600));
  const [layoutViewport,setLayoutViewport]=useState(()=>({
    width:typeof window!=="undefined"?Math.max(1,Math.round(Math.min(window.innerWidth,document.documentElement.clientWidth||window.innerWidth))):390,
    height:typeof window!=="undefined"?Math.max(1,Math.round(Math.min(window.innerHeight,document.documentElement.clientHeight||window.innerHeight))):844,
    safeAreaTop:0,
    safeAreaBottom:0,
  }));
  const [visibleViewport,setVisibleViewport]=useState(()=>({height:typeof window!=="undefined"?Math.max(1,Math.round(Math.min(window.visualViewport?.height??window.innerHeight,window.innerHeight,document.documentElement.clientHeight||window.innerHeight))):844,offsetTop:typeof window!=="undefined"?Math.max(0,Math.round(window.visualViewport?.offsetTop??0)):0}));
  const [homeRecovery,setHomeRecovery]=useState(false);
  const homeLayoutLatch=useRef(false),homeRecoveryLatch=useRef(false);
  useEffect(()=>{const tick=()=>setTime(new Date().toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit",hour12:false}));tick();const id=setInterval(tick,30000);return()=>clearInterval(id)},[]);
  useEffect(()=>{const update=()=>{const narrow=Math.min(window.innerWidth,document.documentElement.clientWidth||window.innerWidth)<=600;setNativeViewport((navigator.maxTouchPoints??0)>0||window.matchMedia("(hover: none) and (pointer: coarse)").matches||narrow)};update();window.addEventListener("resize",update);window.addEventListener("orientationchange",update);return()=>{window.removeEventListener("resize",update);window.removeEventListener("orientationchange",update)}},[]);
  useEffect(()=>{
    const root=document.documentElement,viewport=window.visualViewport,virtualKeyboard=(navigator as Navigator&{virtualKeyboard?:{boundingRect?:{height?:number};addEventListener?:(type:string,listener:EventListener)=>void;removeEventListener?:(type:string,listener:EventListener)=>void}}).virtualKeyboard;
    const safeAreaProbe=document.createElement("div");
    safeAreaProbe.setAttribute("aria-hidden","true");
    // Keep a real box here so iOS/Safari reliably resolves env(safe-area-inset-*) even when the probe has no content.
    safeAreaProbe.style.cssText="position:fixed;visibility:hidden;pointer-events:none;left:0;top:0;width:1px;height:1px;box-sizing:content-box;padding-top:env(safe-area-inset-top,0px);padding-bottom:env(safe-area-inset-bottom,0px)";
    document.body.appendChild(safeAreaProbe);
    let stableHeight=0,stableWidth=0;
    const clear=()=>{root.dataset.chachaKeyboardMode="none";setKeyboard(0)};
    const update=()=>{
      const docWidth=document.documentElement.clientWidth||window.innerWidth,docHeight=document.documentElement.clientHeight||window.innerHeight,innerWidth=Math.max(1,Math.round(window.innerWidth||docWidth)),innerHeight=Math.max(1,Math.round(window.innerHeight||docHeight)),visualWidth=Math.max(1,Math.round(viewport?.width??innerWidth)),visualHeight=Math.max(1,Math.round(viewport?.height??innerHeight)),offsetTop=Math.max(0,Math.round(viewport?.offsetTop??0)),layoutWidth=Math.max(1,Math.round(Math.min(innerWidth,docWidth||innerWidth))),layoutHeight=Math.max(1,Math.round(Math.min(innerHeight,docHeight||innerHeight))),covered=Math.max(0,innerHeight-visualHeight-offsetTop),virtualInset=Math.max(0,Math.round(virtualKeyboard?.boundingRect?.height??0)),visualKeyboard=covered>80&&visualHeight<innerHeight*.85,keyboardVisible=visualKeyboard||virtualInset>80;
      if(!stableHeight||!keyboardVisible)stableHeight=layoutHeight;
      if(!stableWidth||!keyboardVisible)stableWidth=layoutWidth;
      const viewportShrank=visualKeyboard&&visualHeight<stableHeight-80,keyboardOverlay=keyboardVisible&&!viewportShrank?Math.max(covered,virtualInset):0;
      root.style.setProperty("--visual-viewport-width",visualWidth+"px");root.style.setProperty("--visual-viewport-height",visualHeight+"px");root.style.setProperty("--stable-layout-width",stableWidth+"px");root.style.setProperty("--stable-layout-height",stableHeight+"px");root.style.setProperty("--app-viewport-height",(viewportShrank?visualHeight:stableHeight)+"px");root.style.setProperty("--visual-viewport-offset-top",offsetTop+"px");root.dataset.chachaKeyboardMode=keyboardOverlay>0?"overlay":keyboardVisible?"resize":"none";setKeyboard(keyboardOverlay);
      const probeStyle=getComputedStyle(safeAreaProbe),probeRect=safeAreaProbe.getBoundingClientRect();
      const safeAreaTop=Math.max(0,Math.round(Math.max(parseFloat(probeStyle.paddingTop)||0,probeRect.height-1-(parseFloat(probeStyle.paddingBottom)||0))));
      const safeAreaBottom=Math.max(0,Math.round(Math.max(parseFloat(probeStyle.paddingBottom)||0,probeRect.height-1-safeAreaTop)));
      root.style.setProperty("--safe-area-top",safeAreaTop+"px");root.style.setProperty("--safe-area-bottom",safeAreaBottom+"px");
      setLayoutViewport(current=>current.width===stableWidth&&current.height===stableHeight&&current.safeAreaTop===safeAreaTop&&current.safeAreaBottom===safeAreaBottom?current:{width:stableWidth,height:stableHeight,safeAreaTop,safeAreaBottom});
      setVisibleViewport(current=>current.height===visualHeight&&current.offsetTop===offsetTop?current:{height:visualHeight,offsetTop});
    };
    const onVisibility=()=>document.visibilityState==="visible"?update():clear();
    update();viewport?.addEventListener("resize",update);viewport?.addEventListener("scroll",update);virtualKeyboard?.addEventListener?.("geometrychange",update);window.addEventListener("resize",update);window.addEventListener("orientationchange",update);window.addEventListener("pageshow",update);window.addEventListener("pagehide",clear);document.addEventListener("visibilitychange",onVisibility);
    return()=>{viewport?.removeEventListener("resize",update);viewport?.removeEventListener("scroll",update);virtualKeyboard?.removeEventListener?.("geometrychange",update);window.removeEventListener("resize",update);window.removeEventListener("orientationchange",update);window.removeEventListener("pageshow",update);window.removeEventListener("pagehide",clear);document.removeEventListener("visibilitychange",onVisibility);delete root.dataset.chachaKeyboardMode;safeAreaProbe.remove()};
  },[]);
  const displayModeStandalone=typeof window!=="undefined"&&window.matchMedia("(display-mode: standalone)").matches,displayModeFullscreen=typeof window!=="undefined"&&window.matchMedia("(display-mode: fullscreen)").matches,displayModeMinimalUi=typeof window!=="undefined"&&window.matchMedia("(display-mode: minimal-ui)").matches,navigatorStandalone=typeof window!=="undefined"&&(window.navigator as Navigator&{standalone?:boolean}).standalone===true,androidAppReferrer=typeof document!=="undefined"&&document.referrer.startsWith("android-app://"),standalone=displayModeStandalone||displayModeFullscreen||displayModeMinimalUi||navigatorStandalone||androidAppReferrer;
  useLayoutEffect(()=>{document.documentElement.setAttribute("data-chacha-standalone",standalone?"true":"false");return()=>document.documentElement.removeAttribute("data-chacha-standalone")},[standalone]);
  const home=loc.pathname==="/";
  const homeLayout=useMemo(()=>calculateMobileHomeLayout({viewportWidth:layoutViewport.width,viewportHeight:layoutViewport.height,safeAreaTop:layoutViewport.safeAreaTop,safeAreaBottom:layoutViewport.safeAreaBottom}),[layoutViewport]);
  const touchCapable=typeof window!=="undefined"&&((navigator.maxTouchPoints??0)>0||window.matchMedia("(hover: none) and (pointer: coarse)").matches),screenWidth=typeof screen!=="undefined"?screen.width:0,screenHeight=typeof screen!=="undefined"?screen.height:0,screenAvailHeight=typeof screen!=="undefined"?screen.availHeight:0;
  const keyboardOpen=keyboard>0||document.documentElement.dataset.chachaKeyboardMode==="overlay"||document.documentElement.dataset.chachaKeyboardMode==="resize",activeElement=typeof document!=="undefined"?document.activeElement as HTMLElement|null:null,editableFocused=Boolean(activeElement&&(activeElement.matches("input, textarea, select")||activeElement.isContentEditable)),homeKeyboardOpen=keyboardOpen&&editableFocused;
  const homeEnvironmentMatch=isMobileHomeFullCanvasEnvironment({routeIsHome:home,viewportWidth:layoutViewport.width,viewportHeight:layoutViewport.height,screenWidth,screenHeight,screenAvailHeight,touchCapable,portrait:layoutViewport.height>layoutViewport.width,keyboardOpen:homeKeyboardOpen,displayModeStandalone,displayModeFullscreen,displayModeMinimalUi,navigatorStandalone,androidAppReferrer});
  if(homeEnvironmentMatch)homeLayoutLatch.current=true;
  const pwaHomeLayout=home&&nativeViewport&&homeLayout.enabled&&homeLayoutLatch.current;
  const trustedRecoveryHeight=trustedMobileHomeViewportHeight({visualHeight:visibleViewport.height,visualOffsetTop:visibleViewport.offsetTop,innerHeight:window.innerHeight,clientHeight:document.documentElement.clientHeight||window.innerHeight,screenHeight,screenAvailHeight});
  const recoveryLayout=useMemo(()=>calculateMobileHomeFooterRecovery({viewportWidth:layoutViewport.width,viewportHeight:trustedRecoveryHeight,safeAreaTop:layoutViewport.safeAreaTop,safeAreaBottom:layoutViewport.safeAreaBottom}),[layoutViewport.width,layoutViewport.safeAreaTop,layoutViewport.safeAreaBottom,trustedRecoveryHeight]);
  const recoveryCandidate=home&&nativeViewport&&touchCapable&&layoutViewport.width<=600&&layoutViewport.height>layoutViewport.width&&!homeKeyboardOpen&&(homeEnvironmentMatch||homeLayoutLatch.current);
  useEffect(()=>{const onRecovery=(event:Event)=>{const detail=(event as CustomEvent<{recover?:boolean}>).detail;if(!detail?.recover||!recoveryCandidate||homeRecoveryLatch.current)return;homeRecoveryLatch.current=true;setHomeRecovery(true)};window.addEventListener("chacha:home-geometry-recovery",onRecovery);return()=>window.removeEventListener("chacha:home-geometry-recovery",onRecovery)},[recoveryCandidate]);
  const pwaHomeRecovery=home&&homeRecoveryLatch.current&&homeRecovery,appearanceRoot=loc.pathname.startsWith("/appearance"),characterRoot=loc.pathname.startsWith("/characters"),settingsRoot=loc.pathname==="/settings"||loc.pathname.startsWith("/settings/"),meetRoot=loc.pathname.startsWith("/meet"),phoneCheckRoot=loc.pathname.startsWith("/phone-check"),mallRoot=loc.pathname.startsWith("/mall"),musicRoot=loc.pathname.startsWith("/music"),coupleIslandRoot=loc.pathname.startsWith("/couple-island"),forumRoot=loc.pathname.startsWith("/forum"),memoryRoot=loc.pathname.startsWith("/memories"),loreRoot=loc.pathname.startsWith("/lore"),messageFlowRoot=/^\/messages\/(?:contacts\/(?:add|requests)|group\/new|[^/]+\/members\/add)$/.test(loc.pathname),stickerSettingsRoot=loc.pathname==="/settings/stickers",chatSettingsRoot=/^\/messages\/[^/]+\/settings$/.test(loc.pathname),chatChildRoot=/^\/messages\/[^/]+\/(?:settings|search|inner-voice\/(?:character|npc)\/[^/]+)$/.test(loc.pathname),chatRoomRoot=/^\/messages\/[^/]+$/.test(loc.pathname),socialRoot=["/messages/chats","/messages/feed","/messages/contacts","/messages/me"].includes(loc.pathname),nativeTopbarRoot=meetRoot||mallRoot||forumRoot||loreRoot||musicRoot||coupleIslandRoot||stickerSettingsRoot||chatSettingsRoot||messageFlowRoot;
  useLayoutEffect(()=>{const root=document.documentElement;if(pwaHomeRecovery)root.dataset.chachaHomeRecovery="true";else delete root.dataset.chachaHomeRecovery;return()=>{delete root.dataset.chachaHomeRecovery}},[pwaHomeRecovery]);
  const homeStyleLayout=pwaHomeRecovery?recoveryLayout:(pwaHomeLayout?homeLayout:null);
  const shellStyle={"--keyboard-inset":`${keyboard}px`,...(homeStyleLayout?{"--pwa-home-desktop-height":`${homeStyleLayout.desktopHeight}px`,"--pwa-home-row-1":`${homeStyleLayout.rowHeights[0]}px`,"--pwa-home-row-2":`${homeStyleLayout.rowHeights[1]}px`,"--pwa-home-row-3":`${homeStyleLayout.rowHeights[2]}px`,"--pwa-home-row-4":`${homeStyleLayout.rowHeights[3]}px`,"--pwa-home-row-5":`${homeStyleLayout.rowHeights[4]}px`,"--pwa-home-row-6":`${homeStyleLayout.rowHeights[5]}px`,"--pwa-home-gap-1":`${homeStyleLayout.rowGaps[0]}px`,"--pwa-home-gap-2":`${homeStyleLayout.rowGaps[1]}px`,"--pwa-home-gap-3":`${homeStyleLayout.rowGaps[2]}px`,"--pwa-home-gap-4":`${homeStyleLayout.rowGaps[3]}px`,"--pwa-home-gap-5":`${homeStyleLayout.rowGaps[4]}px`,"--pwa-home-row-gap":`${pwaHomeRecovery?recoveryLayout.rowGaps[0]:homeLayout.rowGap}px`,"--pwa-home-top-padding":`${homeStyleLayout.topPadding}px`,"--pwa-home-bottom-padding":`${homeStyleLayout.bottomPadding}px`,"--pwa-home-footer-height":`${homeStyleLayout.footerHeight}px`,"--pwa-home-content-to-dots-gap":`${homeStyleLayout.contentToDotsGap}px`,"--pwa-home-footer-gap":`${homeStyleLayout.dotsToDockGap}px`,"--pwa-home-dock-height":`${homeStyleLayout.dockHeight}px`,"--pwa-home-hero-height":`${homeStyleLayout.heroHeight}px`,"--pwa-home-hero-thumb-size":`${homeStyleLayout.heroThumbSize}px`,...(pwaHomeRecovery?{"--pwa-home-recovery-height":`${recoveryLayout.viewportHeight}px`}:null)}:null)} as React.CSSProperties;
  return <main className="stage"><section className={`phone ${keyboard?"keyboard-open ":""}${standalone?"standalone-mode ":""}${nativeViewport?"native-mobile-viewport ":""}${pwaHomeLayout?"pwa-home-layout-v3 ":""}${recoveryCandidate?"pwa-home-recovery-candidate ":""}${pwaHomeRecovery?"pwa-home-layout-v5-recovery ":""}${stickerSettingsRoot?"sticker-settings-route ":""}${chatSettingsRoot?"chat-settings-route ":""}${messageFlowRoot?"message-flow-route ":""}${forumRoot?"forum-route ":""}${nativeTopbarRoot?"native-topbar-route":""}`} style={shellStyle}><div className="wallpaper"/><header className="status"><b>{time}</b><span className="signals"><Wifi size={15}/><BatteryMedium size={18}/></span></header><div className="screen"><Outlet/></div>{!musicRoot&&<GlobalMusicMiniPlayer/>}{!home&&!socialRoot&&!chatChildRoot&&!appearanceRoot&&!characterRoot&&!settingsRoot&&!meetRoot&&!phoneCheckRoot&&!mallRoot&&!musicRoot&&!coupleIslandRoot&&!forumRoot&&!memoryRoot&&!loreRoot&&!messageFlowRoot&&<button className="back" onClick={()=>chatRoomRoot?nav("/messages/chats"):nav(-1)} aria-label="返回"><ArrowLeft/></button>}</section></main>}export const APP_TOPBAR_CONTENT_HEIGHT=58;
export function AppTopBar({title,onBack,backLabel="返回",actions,className="",titleClassName=""}:{title:string;onBack:()=>void;backLabel?:string;actions?:React.ReactNode;className?:string;titleClassName?:string}){return <header className={`app-topbar ${className}`.trim()} style={{"--app-topbar-content-height":`${APP_TOPBAR_CONTENT_HEIGHT}px`} as React.CSSProperties}><button type="button" className="app-topbar-back" aria-label={backLabel} onClick={onBack}><ChevronLeft/></button><h1 className={`app-topbar-title ${titleClassName}`.trim()}>{title}</h1><div className="app-topbar-actions">{actions}</div></header>}
export function AppHeader({title,subtitle,action}:{title:string;subtitle?:string;action?:React.ReactNode}){return <header className="app-header"><div><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div>{action}</header>}
export function Avatar({text,src,size="md"}:{text:string;src?:string;size?:"sm"|"md"|"lg"}){const [broken,setBroken]=useState(false);useEffect(()=>setBroken(false),[src]);return src&&!broken?<img className={`avatar ${size}`} src={src} alt={`${text}头像`} loading="lazy" onError={()=>setBroken(true)}/>:<span className={`avatar avatar-fallback ${size}`} aria-label={`${text}头像占位`}>{text.slice(0,1)}</span>}
export function Empty({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="empty">{icon}<h3>{title}</h3><p>{text}</p></div>}
export function SheetHeader({title,onClose}:{title:string;onClose:()=>void}){return <div className="sheet-head"><h2>{title}</h2><button type="button" aria-label="关闭" onClick={onClose}><X/></button></div>}
export function Modal({children,onClose}:{children:React.ReactNode;onClose:()=>void}){return <div className="modal-shade" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal">{children}</div></div>}





